apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  - name: Phoenix
    uid: phoenix-ds
    type: yesoreyeram-infinity-datasource
    access: proxy
    editable: false
    jsonData:
      baseURL: ${PHOENIX_BASE_URL:-http://phoenix:6006}
      allowedHosts:
        - ${PHOENIX_BASE_URL:-http://phoenix:6006}
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer ${PHOENIX_API_KEY:-}"

